### ISSUE TITLE
0x5f3759df

### ISSUE THREAD

**Issue by u5n** [pipehappy1/ball_in_box#8]
0x5f3759df

**Comment by pipehappy1** [comment]
run

    git clone https://github.com/pipehappy1/ball_in_box.git
    cd ball_in_box
    bash test_docker_image.sh YOUR_ID

on your machine first then report the log here.

**Comment by Haozun** [comment]
`Total area: 2.9842692302535396`

**Comment by pipehappy1** [comment]
The log should looks like the one shown below. And CHEATING is no good here.

    bash test_docker_image.sh pipehappy1
    pipehappy1
    2018年 06月 01日 星期五 22:41:25 CST
    clone pipehappy1's repository into /home/yguan/workspace/ball_in_box/images/pipehappy1
    Cloning into '/home/yguan/workspace/ball_in_box/images/pipehappy1'...
    remote: Counting objects: 59, done.        
    remote: Total 59 (delta 0), reused 0 (delta 0), pack-reused 59        
    Unpacking objects: 100% (59/59), done.
    Checking connectivity... done.
    clone good
    copy Dockerfile into local directory.
    build docker image
    sha256:b32800528db7ace7f16edfcbb1052c68b83b9bd16be5a6f16498736c92354cb8
    docker build good
    Total area: 0.045023380078333695
    docker run good
    2018年 06月 01日 星期五 22:41:42 CST
    evaluate ends for pipehappy1

**Comment by Haozun** [comment]
上面那个结果是我让别人帮我跑的,他直接用的docker build -t
下面是我自己电脑上跑的
```
Step 14/16 : RUN ls /ball_in_box
 ---> Running in a0ebe937fd88
ball_in_box
ball_in_box.egg-info
requirements.txt
setup.py
Removing intermediate container a0ebe937fd88
 ---> d29615b8c42e
Step 15/16 : RUN ls /ball_in_box/ball_in_box
 ---> Running in 0d8b30a70eb5
__init__.py
area_sum.py
ballinbox.py
ballinbox_iter.py
ballinbox_obsolete.py
validate.py
Removing intermediate container 0d8b30a70eb5
 ---> 7a157b483dd7
Step 16/16 : CMD python3 /ball_in_box/ball_in_box/area_sum.py
 ---> Running in 671cbf4541d1
Removing intermediate container 671cbf4541d1
 ---> fc6d05e1cbfc
Successfully built fc6d05e1cbfc
Successfully tagged pipehappy/haozun:latest
docker build good
Total area: 2.9905795665307235
docker run good
Fri Jun  1 23:01:06 CST 2018
evaluate ends for haozun
```

**Comment by pipehappy1** [comment]
Then you should sit back and relax.

**Comment by Haozun** [comment]
And I have test other 4 people find the sort algorithm is sometimes wrong

**Comment by pipehappy1** [comment]
I see. Please use the ids.txt file to get score for each student, sort it and push to your repository. I'll fetch your score board and update mine.

**Comment by Haozun** [comment]
结果
https://github.com/Haozun/ball_in_box/blob/master/checker/re-result


https://github.com/Haozun/ball_in_box/blob/master/checker/
运行里面的main.py,跑一遍大概耗时半小时
